version: '3.8'

services:
  # Dịch vụ cho môi trường phát triển
  dev:
    # Sử dụng image đã build ở buổi 4 hoặc để compose build
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_app_dev
    ports:
      - "3000:3000"
    volumes:
      # Mount code để có hot-reloading
      - ./client:/app
      # Tip: Ngăn node_modules trên host ghi đè lên node_modules trong container
      - /app/node_modules
    
  # ... (giữ lại phần version và services ở trên) ...
  # Thêm 2 dịch vụ mới này vào dưới service 'dev'

  # Dịch vụ cho ứng dụng React production
  app:
    build:
      context: .
      dockerfile: Dockerfile # Sử dụng Dockerfile production
    container_name: react_app_prod
    # KHÔNG cần 'ports' ở đây nữa, vì Nginx sẽ xử lý việc tiếp xúc với bên ngoài

  # Dịch vụ cho Nginx Reverse Proxy
  nginx:
    image: nginx:1.21-alpine # Dùng image Nginx chính thức
    container_name: nginx_proxy
    ports:
      - "80:80" # Mở cổng 80 ra thế giới bên ngoài
    volumes:
      # Mount file cấu hình Nginx của chúng ta vào trong container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app # Đảm bảo service 'app' khởi động trước 'nginx'
