# Giai đoạn 1: Lấy image cơ sở là Node.js
FROM node:16-alpine

# Thiết lập thư mục làm việc bên trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào TRƯỚC
# để tận dụng Docker layer cache.
# Lệnh RUN npm install chỉ chạy lại khi các file này thay đổi.
COPY client/package*.json ./

# Cài đặt các gói phụ thuộc
RUN npm install

# Sao chép phần còn lại của mã nguồn ứng dụng client
COPY client/. ./

# Mặc định, React dev server chỉ chấp nhận kết nối từ localhost.
# Thiết lập biến môi trường này để nó chấp nhận kết nối từ mọi nơi.
ENV HOST=0.0.0.0

# Thông báo rằng container sẽ lắng nghe trên cổng 3000
EXPOSE 3000

# Lệnh mặc định để khởi chạy container
CMD ["npm", "start"]
